name: build
on: [push]

jobs:
  build:
    name: cargo build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: unity-guid-rewriter
          path: target/release/unity-guid-rewriter.exe
